version : 2
jobs:
  build:
    docker:
      - image: circleci/python:3

    steps:
      - checkout

      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Install SAM
          command: sudo pip install aws-sam-cli
      - run:
          name: Create S3 Bucket
          command: aws s3api create-bucket --bucket serverless-cicd-example-practise-today --region us-east-1
      - run:
          name: Deploy with SAM 
          command: sam deploy --s3-bucket serverless-cicd-example-practise-today --stack-name example-cicd-project --region us-east-1 --capabilities CAPABILITY_IAM --parameter-overrides MyPhoneNumber=$MY_PHONE_NUMBER
